Vnn = 'H:/Vietnamese word representations/Raw news data (no dupplicate)/word_vectors/vnn.json'
Vnexpress = 'H:/Vietnamese word representations/Raw news data (no dupplicate)/word_vectors/vnexpress.json'
Thanhnien = 'H:/Vietnamese word representations/Raw news data (no dupplicate)/word_vectors/thanhnien.json'
Dantri = 'H:/Vietnamese word representations/Raw news data (no dupplicate)/word_vectors/dantri.json'
Tuoitre = 'H:/Vietnamese word representations/Raw news data (no dupplicate)/word_vectors/tuoitre.json'
Vtv = 'H:/Vietnamese word representations/Raw news data (no dupplicate)/word_vectors/vtv.json'
